### ISSUE TITLE
E492: Not an editor command: VAMActivate matchit.zip vim-addon-commenting

### ISSUE THREAD

**Issue by MortalCatalyst** [MarcWeber/vim-addon-manager#166]
I did a VAMUpdateActivated today and all but VAM updated since then it hasn't worked.

I removed all plugins and directories and reisntalled my vimrc from git

https://github.com/MortalCatalyst/emacs/blob/master/.vimrc

Now however VAM fails to install plugins again as below for all plugins

sayth@:~$ vim
Error detected while processing /home/sayth/.vimrc:
line   21:
E492: Not an editor command: VAMActivate matchit.zip vim-addon-commenting

**Comment by ZyX-I** [comment]
It appears that I did `git push -f` to update rebased `extended-autoload` branch without pulling master first and thus accidently pushed outdated `master` as well.

@MarcWeber Do you have a backup? Last thing I found is `refs/pull/164/merge` on github.

**Comment by MarcWeber** [comment]
@ZyX-I When did this happen? Recently or many days ago? Of course I have a backup. Just noticed that upstream was changed by -f (throwing away some commits, eg finally removing the vim2nix because its hosted in its own repo now)

**Comment by MarcWeber** [comment]
I've just pushed corrected-master-without-forced-push. The last "backed up correct hash" was
fda9d2f, " moving nix.vim into github.com/MarcWeber/vim-addon-vim2nix" at 2014-12-03.
If you think that your force pushing is very recent just make that new branch master (git reset --hard origin/corrected-master-without-forced-push) - otherwise we should rebase my changes on top of your history - whatever is likely to cause less problems to most users.

**Comment by ZyX-I** [comment]
@MarcWeber This happened early today or late yesterday. Force pushed *master* was rather out of date. No need to rebase anything in master: everything I did happened in `extended-autoload` branch, just push without `-f` newer master.
