### ISSUE TITLE
Help with post-install/post-update

### ISSUE THREAD

**Issue by chadrien** [MarcWeber/vim-addon-manager#168]
In the docs, I seemed to have read that we can specify post install/update commands, but I can't make it work.

I use a scripts file (`call vam#Scripts('~/.vim/vim-scripts', {'tag_regex': '.*'})`) and I'm trying to make the magic happen like this:

```
{'name': 'vimproc', 'post-install': 'make', 'post-update': 'make'}
```

So basically I'd like the command `make` to be ran after plugin installation/update.

```bash
rm -rf ~/.vim/vim-addons/vimproc ; vim
```

The plugin is installed but the `make` command isn't called.

Am I missing something?

**Comment by ZyX-I** [comment]
You must

1. Use VimL commands and *not* shell commands.
2. VimL commands must not depend on the current working directory. How directory where plugin is installed to can be obtained is described in the documentation.
3. `post-install` and `post-update` are hook names. In addon-info.json file they must be present with `-hook` suffix.
4. `addon-info.json` is JSON file. JSON does not define single-quoted strings and, though this actually works due to currently used implementation, you should not depend on it.

And I have no idea *how* “you are trying to make the magic happen”. The example dictionary does not look like an addon-info file or like a change to vim-pi database.

**Comment by chadrien** [comment]
Hum I see.

The file I describe is not a `addon-info.json` but a VAM file loaded with `call vam#Scripts` (as I said in the issue description).

So if I got you right hooks only trigger if defined in the `addon-info.json` of the install plugin, right?
If so, is there a way to define these hooks from a VAM user point of view?

My precise "problem" is the following:

* I want to install the [vimproc](https://github.com/Shougo/vimproc.vim) plugin (it does not contain a `addon-info.json` file).
* Vimproc require a `.so` file to be generated using the `make` command
* Therefore to automate my VIM installation, I'd like `make` to be ran automatically after the installation/update of vimproc

**Comment by ZyX-I** [comment]
@chadrien What is the “install plugin”? VAM has no plugins. In case plugin is missing addon-info file it may be defined in vim-pi database. You can also use your own function in place of `vam_known_repositories#Pool` that will e.g. call `vam_known_repositories#Pool` and patch the result with necessary information about hooks. Only works for plugins that miss `addon-info.json` file.

Another alternative are global hooks: :h VAM-post_install_hook_functions. Called functions receive enough information to limit function effect to needed plugin only.

**Comment by chadrien** [comment]
"install plugin" was a typo for "installed plugin" :wink: 

I'll have a look to `vam_known_repositories#Pool` and global hooks, thanks.
