### ISSUE TITLE
stuck in configuration

### ISSUE THREAD

**Issue by StephaneKazmierczak** [MarcWeber/vim-addon-manager#183]
I am using WLS and vam is correctly installed I have a few packages installed already (from apt): 
editexisting, justify, matchit, youcompleteme 

and whereis vam => /usr/bin/vam 

but if I try to configure my vim.rc script to use vam:
 
set nocompatible | filetype indent plugin on | syn on
set runtimepath+='/usr/bin/vam'
call vam#ActivateAddons(['scrooloose/syntastic'])

then i am getting Unknown function: vam#ActivateAddons

**Comment by ZyX-I** [comment]
/usr/bin/vam is not a valid place for VAM, /usr/bin is for executable files and whatever you add to `&runtimepath` is a directory. Also you have invalid `:set` syntax, you must not use single quotes there because what you have actually written is “add directory `./'/usr/bin/vam'` to &runtimepath” where all quotes are literal quotes.

**Comment by StephaneKazmierczak** [comment]
Thank you, I am still getting exact same error, I also found this https://vi.stackexchange.com/questions/7249/using-vim-addon-manager 
now I wander if it is related

**Comment by ZyX-I** [comment]
@StephaneKazmierczak If you installed VAM through `apt-get` then you did *not* get VAM from this repository. For some reason @MarcWeber has selected the same name, though I saw that vim-addon-manager only on debian and even there it is stagnating and not very popular.

**Comment by StephaneKazmierczak** [comment]
thank you so much for this confirmation
