### ISSUE TITLE
two many "press any key to continue" when :UpdateAddons

### ISSUE THREAD

**Issue by stardiviner** [MarcWeber/vim-addon-manager#58]
I have many plugins. If I execute command :UpdateAddons, Then I will need to press a lot of key to continue update. Can you let VAM automatically update next addon if no error occurs. Or save all error in buffer. the press some key to check out all errors.
And I found :UninstallUnloadedAddons has same issus too.

**Comment by clangpp** [comment]
I want to avoid the "Press ENTER or type command to continue", but would like the downloading process to be shown, can you help add another mode rather than "bang" and "system" to help with that?

I think the implementation would be changing [this](https://github.com/MarcWeber/vim-addon-manager/blob/872f9302cf0eb8e9cb6259ea4f329d2265f9e32d/autoload/vam/utils.vim#L68-74) into:

```
  if s:c.shell_commands_run_method[-4:] is# 'bang'
    execute '!'.a:cmd
  **elseif s:c.shell_commands_run_method is# 'progress'
    execute 'silent !'.a:cmd**
  elseif s:c.shell_commands_run_method is# 'system'
    call vam#Log(system(a:cmd), 'None')
  else
    throw 'Unknown run method: '.s:c.shell_commands_run_method
  endif
```

**Comment by MarcWeber** [comment]
I don't have time to work on it. Consider giving vundle or NeoBundle a try if this is too annoying.
If you proivde a patch we'll apply it.

In the long run installation code should eventually moved into a full blown package manager instead.
